const defaultPirates = [
    {
        id: "1",
        img: require("../../../assets/img/Monkey_D._Luffy's_Current_Wanted_Poster.png"),
        name: "Luffy",
        reward: 1.5e9,
        isCaptured: false,
    },
    {
        id: "2",
        img: require("../../../assets/img/Brook's_Concert_Wanted_Poster.png"),
        name: "Brook",
        reward: 83e6,
        isCaptured: false,
    },
    {
        id: "3",
        img: require("../../../assets/img/Buggy's_Wanted_Poster.png"),
        name: "Buggy",
        reward: 15e6,
        isCaptured: false,
    },
    {
        id: "4",
        img: require("../../../assets/img/Charlotte_Linlin_Wanted_Poster.png"),
        name: "Charlotte Linlin",
        reward: 4388e6,
        isCaptured: false,
    },
    {
        id: "5",
        img: require("../../../assets/img/God_Usopp's_Wanted_Poster.png"),
        name: "Usopp",
        reward: 2e8,
        isCaptured: false,
    },
    {
        id: "6",
        img: require("../../../assets/img/Jinbe's_Current_Wanted_Poster.png"),
        name: "Jinbe",
        reward: 438e6,
        isCaptured: false,
    },
    {
        id: "7",
        img: require("../../../assets/img/Kaidou_Wanted_Poster.png"),
        name: "Kaidou",
        reward: 46111e5,
        isCaptured: false,
    },
    {
        id: "8",
        img: require("../../../assets/img/Law's_Wanted_Poster.png"),
        name: "Law",
        reward: 5e8,
        isCaptured: false,
    },
    {
        id: "9",
        img: require("../../../assets/img/Marshall_D._Teach_Wanted_Poster.png"),
        name: "Teach",
        reward: 22476e5,
        isCaptured: false,
    },
    {
        id: "10",
        img: require("../../../assets/img/Nami's_Current_Wanted_Poster.png"),
        name: "Nami",
        reward: 66e5,
        isCaptured: false,
    },
    {
        id: "11",
        img: require("../../../assets/img/Nico_Robin's_Current_Wanted_Poster.png"),
        name: "Robin",
        reward: 13e7,
        isCaptured: false,
    },
    {
        id: "12",
        img: require("../../../assets/img/Roronoa_Zoro's_Current_Wanted_Poster.png"),
        name: "Zoro",
        reward: 320e6,
        isCaptured: false,
    },
    {
        id: "13",
        img: require("../../../assets/img/Sabo's_Wanted_Poster.png"),
        name: "Sabo",
        reward: 602e6,
        isCaptured: false,
    },
    {
        id: "14",
        img: require("../../../assets/img/Sanji's_Current_Wanted_Poster.png"),
        name: "Sanji",
        reward: 33e7,
        isCaptured: false,
    },
    {
        id: "15",
        img: require("../../../assets/img/Shanks_Wanted_Poster.png"),
        name: "Shanks_Wanted_Poster",
        reward: 40489e5,
        isCaptured: false,
    },
    {
        id: "16",
        img: require("../../../assets/img/Tony_Tony_Chopper's_Current_Wanted_Poster.png"),
        name: "Chopper",
        reward: 100,
        isCaptured: false,
    },
]

export default defaultPirates
